### ISSUE TITLE
'ImportError: No module named termios' when run 'exmaple_methods.py' on Windows

### ISSUE THREAD

**Issue by proline827** [cmap/l1ktools#11]
Traceback (most recent call last):
  File "C:\Users\Anaconda\Lib\site-packages\example_methods.py", line 5, in <module>
    import cmap.io.gct as gct
  File "C:\Users\Anaconda\Lib\site-packages\cmap\io\gct.py", line 16, in <module>
    import cmap.util.progress as update
  File "C:\Users\Anaconda\Lib\site-packages\cmap\util\progress.py", line 8, in <module>
    import blessings
  File "C:\Users\Anaconda\Lib\site-packages\blessings\__init__.py", line 20, in <module>
    from termios import TIOCGWINSZ
ImportError: No module named termios

termios is Unix dependent
Is there any way to keep running in Windows?

**Comment by tnat1031** [comment]
Hi @proline827 

Just pushed a new branch called remove-progress-bar. Can you please check that out and see if it works for you? Basically just removed any calls to the progress bar functions, which are nice to have but do not impact the core functionality of the code.

Thanks a lot,
Ted
